name: vue-app

services:
  front-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    develop:
      target: dev
      watch:
        - path: ./src
          target: /app/src
          action: sync
    ports:
      - 5173:5173
    profiles: [dev]

  front-prod:
    build:
      context: ../
      target: production
      dockerfile: docker/Dockerfile
    develop:
      target: production
      watch:
        - path: ./src
          target: /app/src
          action: sync
    ports:
      - 5174:5174
    profiles: [production]
