name: vue-app

services:
  front:
    container_name: vue-app
    build:
      target: production
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 5174:5174
    profiles: [production]

  front-dev:
    container_name: vue-app-dev
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev

    develop:
      target: dev
      watch:
        - path: ./src
          target: /app/src
          action: sync
    ports:
      - 5173:5173
    profiles: [dev, front-dev]
